/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,ts,tsx}"],
  theme: {
    container: false,
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-elevated": "var(--bg-elevated)",
        surface: "var(--surface)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        text: "var(--text)",
        "text-muted": "var(--text-muted)",
        "text-subtle": "var(--text-subtle)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-contrast": "var(--accent-contrast)",
        gold: "var(--gold)",
        success: "var(--success)",
        warning: "var(--warning)",
        danger: "var(--danger)",
      },
      fontFamily: {
        display: "var(--font-display)",
        sans: "var(--font-sans)",
        mono: "var(--font-mono)",
      },
      fontSize: {
        display: ["var(--fs-display)", { lineHeight: "1.05" }],
        h1: ["var(--fs-h1)", { lineHeight: "1.1" }],
        h2: ["var(--fs-h2)", { lineHeight: "1.15" }],
        h3: ["var(--fs-h3)", { lineHeight: "1.2" }],
        "body-lg": ["var(--fs-body-lg)", { lineHeight: "1.6" }],
        body: ["var(--fs-body)", { lineHeight: "1.6" }],
        small: ["var(--fs-small)", { lineHeight: "1.5" }],
        mono: ["var(--fs-mono)", { lineHeight: "1.4" }],
        eyebrow: ["var(--fs-eyebrow)", { lineHeight: "1.3" }],
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        7: "var(--space-7)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
      },
      maxWidth: {
        container: "var(--container)",
        "container-wide": "var(--container-wide)",
        "container-narrow": "var(--container-narrow)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      boxShadow: {
        none: "var(--shadow-none)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
      },
      transitionDuration: {
        fast: "var(--dur-fast)",
        base: "var(--dur-base)",
        slow: "var(--dur-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        out: "var(--ease-out)",
      },
      zIndex: {
        header: "var(--z-header)",
        overlay: "var(--z-overlay)",
      },
    },
  },
  plugins: [],
};
